//! A short name for exactly what a search was, so nobody runs it twice.
//!
//! This is the answer to the problem that produced this project's most embarrassing artefact:
//! five contributors submitting **the same 430 names**, two of them byte for byte identical
//! across every file. Nobody did anything wrong. The general search is deterministic, its inputs
//! on a fresh clone are the same everywhere -- the committed beginning and ending lists, and the
//! published tables -- and so it returns the same names to everybody who runs it first. The
//! second person to run it was never going to find anything else.
//!
//! Telling people to "avoid duplicates" cannot fix that, because they had no way to know. What
//! fixes it is for the search to recognise itself: a digest of everything that decides what a
//! pass will find, carried in the submission, and checked before the next pass starts. Then the
//! second person is told, in the first second, that this exact search has already been run to
//! exhaustion by somebody -- and goes and does something else, which is the entire point.
//!
//! What goes in is only what changes the *answer*: the method, the game, the pools, the lists,
//! and the corpus. Not the time, not the machine, not the thread count. Two runs with the same
//! fingerprint would find the same names; two runs with different fingerprints might not.
//!
//! **A count of what this machine happens to hold may never go in.** That is not a style rule,
//! it is the whole difference between a guard that works and the one this project shipped for a
//! month. The general search used to mix in `seed lines`, `pieces` and `wanted`: the first counts
//! the gitignored `findings/` tree, the second follows from it, and the third moves whenever
//! anybody opens a pull request. Measured across three contributors running the *same* method on
//! the same day, `seed lines` read 3,383,984, 5,957,759 and 3,257,412 -- so the same search
//! fingerprinted differently on every machine, one method grew 48 distinct fingerprints,
//! `state/swept.txt` reached 196 rows, and the guard never once fired while everybody re-ground
//! the same ground.
//!
//! The distinction is between a *count* and a *content digest*, and it is the whole of the rule.
//! A digest of the names a pass will actually draw on says which search this is, and two
//! contributors holding the same material still agree on it; a count of how many there were says
//! only how much of somebody's disk was involved, which no two machines will ever answer the same
//! way. So a corpus goes in by content or it does not go in at all.
//!
//! Which corpora go in is then a question about each method, and the two answers here are both
//! deliberate. Where the corpus *is* the method -- `images_from_materials` runs on the materials
//! it can see, and `confirm_cw seeds` on the confirmed names and nothing else -- it goes in, and
//! two fresh clones still collide because they hold the same material. Where the corpus is a
//! fraction of a much larger shared one, as the findings tree is against the published tables in
//! a general pass, it stays out: including it would hand every machine a private fingerprint for
//! material whose measured marginal reach was 55 names, then 294, then 51.

use crate::{feed, hash64};

/// Accumulates what a search is, and reduces it to sixteen hex characters.
pub struct Fingerprint {
    state: u64,
}

impl Fingerprint {
    /// Starts from the method's own name, since two different methods over identical inputs are
    /// different searches.
    pub fn of(method: &str) -> Self {
        Self { state: hash64(method) }
    }

    /// A single value that changes the answer: the game, a flag, a mode.
    pub fn with(mut self, label: &str, value: &str) -> Self {
        self.state = feed(self.state, label.as_bytes());
        self.state = feed(self.state, b"=");
        self.state = feed(self.state, value.as_bytes());
        self.state = feed(self.state, b";");
        self
    }

    /// A count that decides the answer -- and only ever one every clone agrees on.
    ///
    /// The size of a candidate list arriving on a pipe qualifies. The size of anything read off
    /// this machine's disk does not: see the note at the top of this file for what that cost.
    pub fn with_count(self, label: &str, count: usize) -> Self {
        self.with(label, &count.to_string())
    }

    /// A list whose *contents* matter but whose order does not.
    ///
    /// Order-independent on purpose. The beginning and ending lists are regenerated by measuring
    /// the corpus, and a regeneration that produces the same entries in a different order is the
    /// same search -- while one that adds a single new ending is not, and must not be mistaken
    /// for it. Summing per-entry hashes gives exactly that: blind to order, sensitive to
    /// membership.
    pub fn with_list<S: AsRef<str>>(mut self, label: &str, entries: &[S]) -> Self {
        let mut total: u64 = 0;
        for entry in entries {
            total = total.wrapping_add(hash64(entry.as_ref()));
        }

        self.state = feed(self.state, label.as_bytes());
        self.state = feed(self.state, b"=");
        self.state = feed(self.state, &total.to_le_bytes());
        self.state = feed(self.state, &(entries.len() as u64).to_le_bytes());
        self.state = feed(self.state, b";");
        self
    }

    /// Sixteen hex characters, which is what goes into the submission notes.
    pub fn finish(self) -> String {
        format!("{:016x}", self.state)
    }
}

/// How many of a list's smallest hashes a sketch keeps.
///
/// The sketch answers "how much do these two lists share", to roughly a tenth. Thirty-two values
/// is 512 characters in a run note -- small enough to sit in every submission, coarse enough that
/// it can only ever say "these are broadly the same ground", which is the only claim worth making
/// from it.
const SKETCH: usize = 32;

/// A summary of a list that survives being compared with a *different* list.
///
/// The fingerprint beside it answers one question perfectly and one not at all: two searches are
/// identical, or they are not. That is what stopped five contributors submitting the same 430
/// names, and it is blind to the far commoner case -- a plan sharing ninety per cent of its stems
/// with one somebody ran last night. Those two fingerprints differ, so nothing warns anybody, and
/// the second run spends an hour to return the first one's names minus a handful.
///
/// `state/swept.txt` holds 264 of those opaque digests and cannot answer a single question about
/// how they relate. This is the part that can: the k smallest hashes of a list estimate how much
/// two lists share, without either side keeping the lists.
///
/// Deliberately not a fingerprint. It cannot decide anything on its own and must never be used to
/// block a run -- an 18% error either way is fine for "you may be re-treading this" and useless
/// for "you are".
pub struct Sketch;

impl Sketch {
    /// Scatters a hash so that "the smallest k" is a fair sample of a list rather than a run of
    /// similar names.
    ///
    /// This is not optional and the reason is worth keeping. FNV-1a barely avalanches on short
    /// strings that share a prefix: `token_70` through `token_74` hash to values 1.1e15 apart, in
    /// order, so the thirty-two smallest hashes of a name list are thirty-two *consecutive names*
    /// rather than a random sample of it. Two lists sharing half their entries then sketched to
    /// entirely different runs and measured as **zero** overlap -- which is exactly the answer
    /// that would have made this feature quietly useless, since asset names are far more
    /// structured than that test was.
    ///
    /// SplitMix64's finalizer, which is a bijection, so it cannot make two different names
    /// collide that did not already.
    pub(crate) fn scatter(mut hash: u64) -> u64 {
        hash ^= hash >> 30;
        hash = hash.wrapping_mul(0xBF58476D1CE4E5B9);
        hash ^= hash >> 27;
        hash = hash.wrapping_mul(0x94D049BB133111EB);
        hash ^ (hash >> 31)
    }

    /// The sketch of a list, as hex. Empty string for an empty list.
    pub fn of<S: AsRef<str>>(items: &[S]) -> String {
        let mut hashes: Vec<u64> =
            items.iter().map(|item| Self::scatter(crate::hash64(item.as_ref()))).collect();
        hashes.sort_unstable();
        hashes.dedup();
        hashes.truncate(SKETCH);

        hashes.iter().map(|hash| format!("{hash:016x}")).collect::<Vec<_>>().join("")
    }

    /// Roughly what share of two sketched lists is common to both, 0.0 to 1.0.
    ///
    /// The k-minimum-values estimator: over the union of the two sketches, the share of values
    /// present in both. Returns `None` when either side is empty, because "no overlap" and
    /// "nothing to compare" are different answers and a caller that conflates them will warn
    /// about every list nobody has sketched yet.
    pub fn overlap(left: &str, right: &str) -> Option<f64> {
        let parse = |text: &str| -> Vec<u64> {
            text.as_bytes()
                .chunks(16)
                .filter(|chunk| chunk.len() == 16)
                .filter_map(|chunk| u64::from_str_radix(std::str::from_utf8(chunk).ok()?, 16).ok())
                .collect()
        };

        let left = parse(left);
        let right = parse(right);
        if left.is_empty() || right.is_empty() {
            return None;
        }

        // Only the smallest k of the *combined* set is a fair sample of the union; beyond that
        // one side simply ran out of values and would look like disagreement.
        let mut union: Vec<u64> = left.iter().chain(right.iter()).copied().collect();
        union.sort_unstable();
        union.dedup();
        union.truncate(SKETCH.min(left.len()).min(right.len()));

        if union.is_empty() {
            return None;
        }

        let in_left: std::collections::HashSet<u64> = left.into_iter().collect();
        let in_right: std::collections::HashSet<u64> = right.into_iter().collect();
        let both = union.iter().filter(|v| in_left.contains(v) && in_right.contains(v)).count();

        Some(both as f64 / union.len() as f64)
    }
}

/// A sketch built from a stream, for searches whose candidates never exist as a list.
///
/// `confirm_list` is handed candidates on a pipe -- tens of millions of them, never collected --
/// so there is no list to sketch and it recorded nothing. That mattered more than it looked:
/// `confirm_list` is the path **every invented method** takes, so the overlap ledger was blind to
/// exactly the half of the project it was built to protect. Only `confirm_cw` and `confirm_plan`
/// carried sketches, which is why one contributor's submissions had them and another's did not.
///
/// Keeps the k smallest scattered hashes seen, which is the same summary `Sketch::of` produces for
/// a list -- so a streamed run and a planned run can be compared with each other.
#[derive(Default)]
pub struct SketchStream {
    /// Smallest first. Kept sorted and truncated rather than heaped: k is 32, so the insert is a
    /// binary search into a 32-element vector and the branch is not taken for the overwhelming
    /// majority of candidates.
    smallest: Vec<u64>,
}

impl SketchStream {
    pub fn new() -> Self {
        Self { smallest: Vec::with_capacity(SKETCH + 1) }
    }

    /// Offers one candidate to the sketch.
    pub fn add(&mut self, text: &str) {
        let value = Sketch::scatter(crate::hash64(text));

        // The common case, and it has to be cheap: already full and this is not small enough.
        if self.smallest.len() == SKETCH && value >= self.smallest[SKETCH - 1] {
            return;
        }

        match self.smallest.binary_search(&value) {
            Ok(_) => return, // a repeat contributes nothing, exactly as the set in `Sketch::of`
            Err(at) => self.smallest.insert(at, value),
        }

        self.smallest.truncate(SKETCH);
    }

    /// The sketch, in the same hex spelling `Sketch::of` writes.
    pub fn finish(&self) -> String {
        self.smallest.iter().map(|value| format!("{value:016x}")).collect::<Vec<_>>().join("")
    }
}

#[cfg(test)]
mod tests {
    /// A streamed sketch and a listed sketch of the same names must be identical, or a run that
    /// streamed its candidates could never be compared with one that planned them -- which is the
    /// whole point of having both.
    #[test]
    fn a_streamed_sketch_matches_the_listed_one() {
        let names: Vec<String> = (0..500).map(|n| format!("mc/mtl_wpn_ak47_{n}")).collect();

        let mut stream = SketchStream::new();
        for name in &names {
            stream.add(name);
        }
        // Offered twice over, since a stream has no way to deduplicate and a list does.
        for name in &names {
            stream.add(name);
        }

        assert_eq!(stream.finish(), Sketch::of(&names));
        assert_eq!(SketchStream::new().finish(), "", "an empty stream sketches to nothing");
    }


    /// A sketch has to say "the same" for the same list and "not the same" for a different one,
    /// and -- the whole point -- something sensible in between.
    #[test]
    fn a_sketch_measures_how_much_two_lists_share() {
        let letters = |from: u32, to: u32| -> Vec<String> {
            (from..to).map(|n| format!("token_{n}")).collect()
        };

        let all = Sketch::of(&letters(0, 200));
        let same = Sketch::of(&letters(0, 200));
        let half = Sketch::of(&letters(100, 300));
        let none = Sketch::of(&letters(1000, 1200));

        assert_eq!(all, same, "the same list must sketch identically");

        let identical = Sketch::overlap(&all, &same).expect("two sketched lists");
        assert!(identical > 0.99, "identical lists should overlap fully, got {identical}");

        let overlapping = Sketch::overlap(&all, &half).expect("two sketched lists");
        assert!(
            (0.1..0.75).contains(&overlapping),
            "half-shared lists should land between, got {overlapping}"
        );

        let apart = Sketch::overlap(&all, &none).expect("two sketched lists");
        assert!(apart < 0.25, "disjoint lists should barely overlap, got {apart}");

        assert!(overlapping < identical, "sharing half must read as less than sharing all");
        assert!(apart < overlapping, "sharing nothing must read as less than sharing half");
    }

    /// The sketch has a second implementation, in `scripts/overlap.py`, which has to produce the
    /// identical string or a plan can never be matched against a recorded run -- and would report
    /// "nothing on record looks like this plan" for every plan, for ever, which is the reassuring
    /// failure rather than the loud one.
    ///
    /// Pinned as a literal on both sides. `scripts/overlap.py` asserts the same value.
    #[test]
    fn the_python_side_computes_the_same_sketch() {
        let list = ["mc/mtl_wpn_ak47", "i_wpn_ak47_c", "zmb/ai/nosferatu", "token_7", "_barrel_c"];

        assert_eq!(
            Sketch::of(&list),
            "272847589166a63e81de050a13ba3960bbc39531c9277735d0b9e574cfee006adb07a4b5dba9ed84",
            "scripts/overlap.py must agree with this byte for byte"
        );
    }

    /// Nothing to compare is not the same answer as nothing in common, and a caller that treats
    /// them alike warns about every run recorded before sketches existed.
    #[test]
    fn an_unsketched_list_is_not_a_disagreement() {
        let something = Sketch::of(&["a_token", "b_token"]);

        assert_eq!(Sketch::overlap("", &something), None);
        assert_eq!(Sketch::overlap(&something, ""), None);
        assert_eq!(Sketch::of::<&str>(&[]), "");
    }
    use super::*;

    /// The property the whole idea rests on: the same search fingerprints the same everywhere,
    /// which is what lets one contributor's submission warn the next contributor off.
    #[test]
    fn the_same_search_gives_the_same_fingerprint() {
        let one = Fingerprint::of("general")
            .with("game", "BLKOPSCW")
            .with_list("endings", &["_01", "_02"])
            .with_count("seeds", 400)
            .finish();

        let two = Fingerprint::of("general")
            .with("game", "BLKOPSCW")
            .with_list("endings", &["_01", "_02"])
            .with_count("seeds", 400)
            .finish();

        assert_eq!(one, two);
        assert_eq!(one.len(), 16);
    }

    /// Re-measuring the lists and getting them back in a different order is the same search.
    #[test]
    fn list_order_does_not_change_it() {
        let forwards = Fingerprint::of("general").with_list("endings", &["_a", "_b", "_c"]).finish();
        let backwards = Fingerprint::of("general").with_list("endings", &["_c", "_b", "_a"]).finish();

        assert_eq!(forwards, backwards);
    }

    /// One more ending is a different search, and must be able to say so -- otherwise the
    /// compounding loop, where every confirmed name widens the lists, would look like a repeat.
    #[test]
    fn one_more_entry_changes_it() {
        let narrow = Fingerprint::of("general").with_list("endings", &["_a", "_b"]).finish();
        let wider = Fingerprint::of("general").with_list("endings", &["_a", "_b", "_c"]).finish();

        assert_ne!(narrow, wider);
    }

    /// A different game over identical lists is a different search.
    #[test]
    fn the_game_is_part_of_it() {
        let cw = Fingerprint::of("general").with("game", "BLKOPSCW").finish();
        let bo4 = Fingerprint::of("general").with("game", "BLKOPS04").finish();

        assert_ne!(cw, bo4);
    }

    /// A list of the same length holding different things is a different search -- a count alone
    /// would not catch that.
    #[test]
    fn contents_matter_not_just_the_count() {
        let one = Fingerprint::of("m").with_list("l", &["_a", "_b"]).finish();
        let two = Fingerprint::of("m").with_list("l", &["_a", "_z"]).finish();

        assert_ne!(one, two);
    }
}
