//! A short name for exactly what a search was, so nobody runs it twice.
//!
//! This is the answer to the problem that produced this project's most embarrassing artefact:
//! five contributors submitting **the same 430 names**, two of them byte for byte identical
//! across every file. Nobody did anything wrong. The general search is deterministic, its inputs
//! on a fresh clone are the same everywhere -- the committed beginning and ending lists, and the
//! published tables -- and so it returns the same names to everybody who runs it first. The
//! second person to run it was never going to find anything else.
//!
//! Telling people to "avoid duplicates" cannot fix that, because they had no way to know. What
//! fixes it is for the search to recognise itself: a digest of everything that decides what a
//! pass will find, carried in the submission, and checked before the next pass starts. Then the
//! second person is told, in the first second, that this exact search has already been run to
//! exhaustion by somebody -- and goes and does something else, which is the entire point.
//!
//! What goes in is only what changes the *answer*: the method, the game, the pools, the lists,
//! and the corpus. Not the time, not the machine, not the thread count. Two runs with the same
//! fingerprint would find the same names; two runs with different fingerprints might not.
//!
//! **A count of what this machine happens to hold may never go in.** That is not a style rule,
//! it is the whole difference between a guard that works and the one this project shipped for a
//! month. The general search used to mix in `seed lines`, `pieces` and `wanted`: the first counts
//! the gitignored `findings/` tree, the second follows from it, and the third moves whenever
//! anybody opens a pull request. Measured across three contributors running the *same* method on
//! the same day, `seed lines` read 3,383,984, 5,957,759 and 3,257,412 -- so the same search
//! fingerprinted differently on every machine, one method grew 48 distinct fingerprints,
//! `state/swept.txt` reached 196 rows, and the guard never once fired while everybody re-ground
//! the same ground.
//!
//! The distinction is between a *count* and a *content digest*, and it is the whole of the rule.
//! `with_list` over the names a pass will actually draw on says which search this is, and two
//! contributors holding the same material still agree; `with_count` over how many of them there
//! were says only how much of somebody's disk was involved, which no two machines will ever
//! answer the same way. So a corpus goes in through `with_list` or it does not go in at all --
//! and the local findings tree does not, because everybody has one, no two are alike, and it
//! grows every pass, which would hand every machine a private fingerprint all over again.

use crate::{feed, hash64};

/// Accumulates what a search is, and reduces it to sixteen hex characters.
pub struct Fingerprint {
    state: u64,
}

impl Fingerprint {
    /// Starts from the method's own name, since two different methods over identical inputs are
    /// different searches.
    pub fn of(method: &str) -> Self {
        Self { state: hash64(method) }
    }

    /// A single value that changes the answer: the game, a flag, a mode.
    pub fn with(mut self, label: &str, value: &str) -> Self {
        self.state = feed(self.state, label.as_bytes());
        self.state = feed(self.state, b"=");
        self.state = feed(self.state, value.as_bytes());
        self.state = feed(self.state, b";");
        self
    }

    /// A count that decides the answer -- and only ever one every clone agrees on.
    ///
    /// The size of a candidate list arriving on a pipe qualifies. The size of anything read off
    /// this machine's disk does not: see the note at the top of this file for what that cost.
    pub fn with_count(self, label: &str, count: usize) -> Self {
        self.with(label, &count.to_string())
    }

    /// A list whose *contents* matter but whose order does not.
    ///
    /// Order-independent on purpose. The beginning and ending lists are regenerated by measuring
    /// the corpus, and a regeneration that produces the same entries in a different order is the
    /// same search -- while one that adds a single new ending is not, and must not be mistaken
    /// for it. Summing per-entry hashes gives exactly that: blind to order, sensitive to
    /// membership.
    pub fn with_list<S: AsRef<str>>(mut self, label: &str, entries: &[S]) -> Self {
        let mut total: u64 = 0;
        for entry in entries {
            total = total.wrapping_add(hash64(entry.as_ref()));
        }

        self.state = feed(self.state, label.as_bytes());
        self.state = feed(self.state, b"=");
        self.state = feed(self.state, &total.to_le_bytes());
        self.state = feed(self.state, &(entries.len() as u64).to_le_bytes());
        self.state = feed(self.state, b";");
        self
    }

    /// Sixteen hex characters, which is what goes into the submission notes.
    pub fn finish(self) -> String {
        format!("{:016x}", self.state)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The property the whole idea rests on: the same search fingerprints the same everywhere,
    /// which is what lets one contributor's submission warn the next contributor off.
    #[test]
    fn the_same_search_gives_the_same_fingerprint() {
        let one = Fingerprint::of("general")
            .with("game", "BLKOPSCW")
            .with_list("endings", &["_01", "_02"])
            .with_count("seeds", 400)
            .finish();

        let two = Fingerprint::of("general")
            .with("game", "BLKOPSCW")
            .with_list("endings", &["_01", "_02"])
            .with_count("seeds", 400)
            .finish();

        assert_eq!(one, two);
        assert_eq!(one.len(), 16);
    }

    /// Re-measuring the lists and getting them back in a different order is the same search.
    #[test]
    fn list_order_does_not_change_it() {
        let forwards = Fingerprint::of("general").with_list("endings", &["_a", "_b", "_c"]).finish();
        let backwards = Fingerprint::of("general").with_list("endings", &["_c", "_b", "_a"]).finish();

        assert_eq!(forwards, backwards);
    }

    /// One more ending is a different search, and must be able to say so -- otherwise the
    /// compounding loop, where every confirmed name widens the lists, would look like a repeat.
    #[test]
    fn one_more_entry_changes_it() {
        let narrow = Fingerprint::of("general").with_list("endings", &["_a", "_b"]).finish();
        let wider = Fingerprint::of("general").with_list("endings", &["_a", "_b", "_c"]).finish();

        assert_ne!(narrow, wider);
    }

    /// A different game over identical lists is a different search.
    #[test]
    fn the_game_is_part_of_it() {
        let cw = Fingerprint::of("general").with("game", "BLKOPSCW").finish();
        let bo4 = Fingerprint::of("general").with("game", "BLKOPS04").finish();

        assert_ne!(cw, bo4);
    }

    /// A list of the same length holding different things is a different search -- a count alone
    /// would not catch that.
    #[test]
    fn contents_matter_not_just_the_count() {
        let one = Fingerprint::of("m").with_list("l", &["_a", "_b"]).finish();
        let two = Fingerprint::of("m").with_list("l", &["_a", "_z"]).finish();

        assert_ne!(one, two);
    }
}
