//! Where everything lives.
//!
//! Every path here is **relative to the repository by default**, so a fresh clone works with no
//! setup and nothing about one person's machine is baked into the code. Anything that does depend
//! on a particular machine -- where a game build was unpacked --
//! is read from `config.toml` and simply absent for most people, because most people are grinding
//! against a captured snapshot and never touch a game file.
//!
//! A search that cannot find its tables reports every published name in the game as a new
//! discovery, so the one rule here is that a missing path is reported rather than guessed at.

use std::path::PathBuf;

use crate::config;

/// Where each thing lives when nobody has configured it: all inside the repository, so a fresh
/// clone works untouched and nothing about one person's machine is implied by the code.
pub const DEFAULT_TABLES: &str = "tables";
pub const DEFAULT_SNAPSHOTS: &str = "snapshots";
pub const DEFAULT_FINDINGS: &str = "findings";
pub const DEFAULT_SUBMISSIONS: &str = "submissions";

/// The hash tables, as csv. These say what the community already resolves, which is the whole of
/// the difference between a discovery and a name somebody published last week.
pub fn tables() -> PathBuf {
    config::path("tables").unwrap_or_else(|| PathBuf::from(DEFAULT_TABLES))
}

/// The captured asset ids, one file per game. This is what a name is confirmed against, and the
/// only thing here that cannot be regenerated without owning the game.
pub fn snapshots() -> PathBuf {
    config::path("snapshots").unwrap_or_else(|| PathBuf::from(DEFAULT_SNAPSHOTS))
}

/// What this machine has confirmed: a file per asset type, plus a folder per run holding only
/// what that run was the first to reach. The run folders are what gets submitted.
pub fn findings() -> PathBuf {
    config::path("findings").unwrap_or_else(|| PathBuf::from(DEFAULT_FINDINGS))
}

/// Where a run's own findings are gathered before being sent.
pub fn submissions() -> PathBuf {
    config::path("submissions").unwrap_or_else(|| PathBuf::from(DEFAULT_SUBMISSIONS))
}

/// The measured beginnings and endings, generated by `scripts/derive_lists.py`. Committed, so a
/// fresh clone can search before it has measured anything itself.
pub const SUFFIX_LIST: &str = "data/suffixes.txt";
pub const PREFIX_LIST: &str = "data/prefixes.txt";

// --- Only needed by whoever owns a game build. Absent for everyone else. ---

/// Strings scraped out of a game build. The only source of real asset names for a title whose
/// build is unhashed, and irrelevant to anyone grinding from a snapshot.
pub fn harvest() -> Option<PathBuf> {
    config::path("harvest")
}

/// A folder of names borrowed from another title. Cold War carries a great deal of Black Ops 4's
/// content, so those names are candidates here even though they are never measured for
/// conventions.
pub fn borrowed() -> Option<PathBuf> {
    config::path("borrowed")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fresh clone must work with no configuration at all, and must not reach outside itself.
    ///
    /// The defaults are asserted rather than the resolved paths, because a machine with a
    /// `config.toml` resolves to whatever that says -- which is the whole point of having one.
    #[test]
    fn the_defaults_are_inside_the_repository() {
        for default in [
            DEFAULT_TABLES,
            DEFAULT_SNAPSHOTS,
            DEFAULT_FINDINGS,
            DEFAULT_SUBMISSIONS,
        ] {
            let path = PathBuf::from(default);
            assert!(path.is_relative(), "{default} should be relative");
            assert!(!default.contains(':'), "{default} should not name a drive");
            assert!(!default.starts_with(".."), "{default} should not escape the repository");
        }
    }

    /// The machine-specific ones are absent rather than wrong when nobody has set them.
    #[test]
    fn a_path_nobody_configured_is_absent() {
        // Whatever this machine's config says, these must be Options rather than a guess at
        // somebody's Desktop.
        let _ = harvest();
        let _ = borrowed();
    }
}
